jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      set -ex
      sudo add-apt-repository -y ppa:hvr/ghc
      sudo apt-get update
      sudo apt-get install cabal-install-3.0 ghc-8.8.1
      sudo update-alternatives --display ghc
      sudo update-alternatives --display cabal
