jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      cabal-8.6.5:
        GHCVER: 8.6.5
        CABALVER: 3.0
      cabal-8.8.1:
        GHCVER: 8.8.1
        CABALVER: 3.0
  variables:
    CABAL_STORE_FOLDER: $(Pipeline.Workspace)/.cabal/store
    CABAL_FLAGS: "-fWerror"
  steps:
  - script: |
      set -ex
      sudo update-alternatives --set opt-ghc /opt/ghc/bin/ghc-${GHCVER}
      sudo update-alternatives --set opt-cabal /opt/cabal/bin/cabal-${CABALVER}
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      ghc --version
      cabal --version

      cabal v2-update

      mkdir -p $(CABAL_STORE_FOLDER)

      sed -i "s%-- store-dir:%store-dir: $(CABAL_STORE_FOLDER)%" $HOME/.cabal/config

      cabal v2-freeze ${CABAL_FLAGS} --enable-tests

  - task: Cache@2
    inputs:
      key: '"cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"  | cabal.project.freeze'
      restoreKeys: |
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"
      path: $(Pipeline.Workspace)/.cabal/store

  - script: |
      set -ex
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      case ${CABALVER%%.*} in
        2) export CABALDFLAGS=""
           ;;
        3) export CABALDFLAGS="--test-show-details=streaming"
           ;;
      esac

      cabal v2-test ${CABAL_FLAGS} ${CABALDFLAGS} ucd:ucd-test-xml ucd:ucd-test-inspection

- job: windows
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      ghc-8.8.1:
        GHCVER: 8.8.1
  variables:
    CABAL_FLAGS: "-fWerror"
  steps:
  - pwsh: |
      Set-PSDebug -Trace 2

      choco install cabal
      choco install ghc --version=${GHCVER}

      refreshenv

      echo "${env:PATH}"

      $env:PATH += ";C:\ProgramData\chocolatey\lib\ghc\tools\ghc-${GHCVER}\bin"

      cabal --version
      ghc --version

      cabal v2-update

      dir $(Pipeline.Workspace)

      cabal v2-test --test-show-details=streaming ucd:ucd-test-xml ucd:ucd-test-inspection
