jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      cabal-8.6.5:
        GHCVER: 8.6.5
        CABALVER: 2.4
      cabal-8.8.1:
        GHCVER: 8.8.1
        CABALVER: 3.0
  steps:
  - script: |
      set -ex
      sudo update-alternatives --set opt-ghc /opt/ghc/bin/ghc-${GHCVER}
      sudo update-alternatives --set opt-cabal /opt/cabal/bin/cabal-${CABALVER}
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      ghc --version
      cabal --version

      cabal v2-update

      case ${CABALVER%%.*} in
        2) export CABALFLAGS="--show-details=streaming"
           ;;
        3) export CABALFLAGS="--test-show-details=streaming"
           ;;
      esac

      cabal v2-test --help

      cabal v2-test ${CABALFLAGS} ucd:ucd-test-xml ucd:ucd-test-inspection
