jobs:
- job: linuxCabal
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      cabal-8.6.5:
        GHCVER: 8.6.5
        CABALVER: 3.0
      cabal-8.8.1:
        GHCVER: 8.8.1
        CABALVER: 3.0
  variables:
    CABAL_STORE_FOLDER: $(Pipeline.Workspace)/.cabal/store
    CABAL_FLAGS: "-fWerror"
  steps:
  - script: |
      set -ex
      sudo update-alternatives --set opt-ghc /opt/ghc/bin/ghc-${GHCVER}
      sudo update-alternatives --set opt-cabal /opt/cabal/bin/cabal-${CABALVER}
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      ghc --version
      cabal --version

      cabal v2-update

      cabal user-config update --augment="store-dir: $(CABAL_STORE_FOLDER)"

      cabal v2-freeze ${CABAL_FLAGS} --enable-tests

  - task: Cache@2
    inputs:
      key: '"cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"  | cabal.project.freeze'
      restoreKeys: |
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)"
      path: $(Pipeline.Workspace)/.cabal/store

  - script: |
      set -ex
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      case ${CABALVER%%.*} in
        2) export CABALDFLAGS=""
           ;;
        3) export CABALDFLAGS="--test-show-details=streaming"
           ;;
      esac

      cabal v2-test ${CABAL_FLAGS} ${CABALDFLAGS} ucd:ucd-test-xml ucd:ucd-test-inspection

- job: linuxStack
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      lts-14.16:
        RESOLVER: lts-14.16
  variables:
    STACK_ROOT: $(Pipeline.Workspace)/.stack
  steps:
  - script: |
      set -ex
      stack --version

      echo "resolver: ${RESOLVER}" >> stack.yaml

      stack test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection --dry-run
      stack test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection --dry-run 2>&1 | tee stack.dry-run.log

      cat stack.yaml.lock
      cat stack.dry-run.log

  - task: Cache@2
    inputs:
      key: '"stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock | stack.dry-run.log'
      restoreKeys: |
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)"
      path: $(STACK_ROOT)

  - script: |
      set -ex
      stack test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection

- job: windowsCabal
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      ghc-8.8.1:
        GHCVER: 8.8.1
        CABALVER: 3.0.0.0
  variables:
    CABAL_FLAGS: "-fWerror"
    CABAL_STORE_FOLDER: $(Pipeline.Workspace)\_cabal\store
  steps:
  - pwsh: |
      Set-PSDebug -Trace 2

      choco install cabal --version=${env:CABALVER}
      choco install ghc --version=${env:GHCVER}

      $env:PATH += ";C:\ProgramData\chocolatey\lib\ghc\tools\ghc-${env:GHCVER}\bin"

      cabal --version
      ghc --version

      cabal v2-update

      cabal user-config update --augment="store-dir: $(CABAL_STORE_FOLDER)"

      cabal v2-freeze ${CABAL_FLAGS} --enable-tests

  - task: Cache@2
    inputs:
      key: '"cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"  | cabal.project.freeze'
      restoreKeys: |
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)"
      path: $(CABAL_STORE_FOLDER)

  - pwsh: |
      Set-PSDebug -Trace 2
      $env:PATH += ";C:\ProgramData\chocolatey\lib\ghc\tools\ghc-${env:GHCVER}\bin"

      cabal v2-test --test-show-details=streaming ucd:ucd-test-xml

- job: windowsStack
  pool:
    vmImage: 'windows-latest'
  strategy:
    matrix:
      lts-14.16:
        RESOLVER: lts-14.16
  variables:
    STACK_ROOT: $(Pipeline.Workspace)\_stack
  steps:
  - bash: |
      set -ex

      curl -sSkL http://www.stackage.org/stack/windows-x86_64 -o /usr/bin/stack.zip
      unzip -o /usr/bin/stack.zip -d /usr/bin/

      stack --version

      echo "resolver: ${env:RESOLVER}" >> stack.yaml

      stack --no-terminal test --pedantic ucd:ucd-test-xml --dry-run
      stack --no-terminal test --pedantic ucd:ucd-test-xml --dry-run 2>&1 | tee stack.dry-run.log

      cat stack.yaml.lock
      cat stack.dry-run.log

  - task: Cache@2
    inputs:
      key: '"stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock | stack.dry-run.log'
      restoreKeys: |
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)"
      path: $(STACK_ROOT)

  - bash: |
      set -ex
      stack --no-terminal test --pedantic ucd:ucd-test-xml

- job: macOSCabal
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      ghc-8.6.5:
        GHCVER: 8.6
      ghc-8.8.1:
        GHCVER: 8.8
  variables:
    CABAL_STORE_FOLDER: $(Pipeline.Workspace)/.cabal/store
    CABAL_FLAGS: "-fWerror"
  steps:
  - bash: |
      set -ex

      brew install "ghc@${GHCVER}" cabal-install

      export PATH="/usr/local/opt/ghc@${GHCVER}/bin:$PATH"

      ghc --version
      cabal --version

      cabal v2-update

      cabal user-config update --augment="store-dir: $(CABAL_STORE_FOLDER)"

      cabal v2-freeze ${CABAL_FLAGS} --enable-tests

  - task: Cache@2
    inputs:
      key: '"cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | cabal.project.freeze'
      restoreKeys: |
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)"
      path: $(CABAL_STORE_FOLDER)

  - bash: |
      set -ex

      export PATH="/usr/local/opt/ghc@${GHCVER}/bin:$PATH"

      cabal v2-test ${CABAL_FLAGS} --test-show-details=streaming ucd:ucd-test-xml ucd:ucd-test-inspection

- job: macOSStack
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      lts-14.16:
        RESOLVER: lts-14.16
  variables:
    STACK_ROOT: $(Pipeline.Workspace)/.stack
  steps:
  - script: |
      set -ex

      brew install haskell-stack icu4c

      stack --version

      echo "resolver: ${RESOLVER}" >> stack.yaml

      stack test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection --dry-run
      stack test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection --dry-run 2>&1 | tee stack.dry-run.log

      cat stack.yaml.lock
      cat stack.dry-run.log

  - task: Cache@2
    inputs:
      key: '"stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock | stack.dry-run.log'
      restoreKeys: |
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)" | stack.yaml.lock
        "stack.root" | "$(Agent.OS)" | "$(RESOLVER)"
      path: $(STACK_ROOT)

  - script: |
      set -ex
      stack --extra-include-dirs "/usr/local/opt/icu4c/include" --extra-lib-dirs "/usr/local/opt/icu4c/lib" test --pedantic ucd:ucd-test-xml ucd:ucd-test-inspection

- job: genLinux
  pool:
    vmImage: 'ubuntu-latest'
  variables:
    GHCVER: 8.8.1
    CABALVER: 3.0
    CABAL_STORE_FOLDER: $(Pipeline.Workspace)/.cabal/store
    CABAL_FLAGS: "-fWerror -f-threaded"
  steps:
  - script: |
      set -ex
      sudo update-alternatives --set opt-ghc /opt/ghc/bin/ghc-${GHCVER}
      sudo update-alternatives --set opt-cabal /opt/cabal/bin/cabal-${CABALVER}
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH
      ghc --version
      cabal --version

      cabal v2-update

      cabal user-config update --augment="store-dir: ${CABAL_STORE_FOLDER}"

      cabal v2-freeze ${CABAL_FLAGS} --enable-tests

  - task: Cache@2
    inputs:
      key: '"cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)" | cabal.project.freeze'
      restoreKeys: |
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)" | "$(CABALVER)"
        "cabal.store" | "$(Agent.OS)" | "$(GHCVER)"
      path: $(CABAL_STORE_FOLDER)

  - script: |
      set -ex
      export PATH=/opt/ghc/bin:/opt/cabal/bin:$PATH

      mkdir -p reference/ucd
      mv -v {,reference/}ucd/generated

      cabal v2-run ${CABAL_FLAGS} gen:ucd

      diff -sr {reference/,}ucd/generated/cbits
      diff -sr {reference/,}ucd/generated/hs

      cabal v2-test ${CABAL_FLAGS} ucd:ucd-test
